# Generated by Django 3.2.6 on 2021-08-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_officialcontactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMambarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('facebook_link', models.CharField(max_length=500)),
                ('instagram_link', models.CharField(max_length=500)),
                ('linkdin_link', models.CharField(max_length=500)),
            ],
        ),
    ]
