# Generated by Django 3.2.6 on 2021-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_teammambarprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammambarprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammambarprofile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammambarprofile',
            name='linkdin_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
