# Generated by Django 3.2.6 on 2021-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20210828_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammambarprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
