# Generated by Django 3.2.6 on 2021-08-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_teammambarprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
