# Generated by Django 3.2.6 on 2021-08-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='profile_picture',
        ),
    ]
