# Generated by Django 3.2.6 on 2021-08-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0007_remove_clients_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
