# Generated by Django 6.0 on 2026-01-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammambarprofile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='teammambarprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='teammambarprofile',
            name='linkdin_link',
        ),
    ]
