# Generated by Django 6.0 on 2026-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_remove_teammambarprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=500)),
                ('Details', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
