# Generated by Django 6.0 on 2026-01-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0011_casestudy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='Details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='Title',
            new_name='title',
        ),
    ]
